name = "hyenimc-curseforge-proxy"
main = "src/index.js"
compatibility_date = "2024-01-01"

# KV namespace for rate limiting
kv_namespaces = [
  { binding = "RATE_LIMIT", id = "49ce1206ab5641d69ca96345b1650207" }
]

# Environment variables (set via wrangler secret)
# CURSEFORGE_API_KEY - Set via: wrangler secret put CURSEFORGE_API_KEY

[env.production]
workers_dev = false
routes = [
  { pattern = "hyenimc-cf-proxy.workers.dev/*", zone_name = "workers.dev" }
]
